### ISSUE TITLE
Verify that the ZWESIS01 module is valid in STEPLIB at startup

### ISSUE THREAD

**Issue by ifakhrutdinov** [zowe/zowe-common-c#18]
A recent bug in the deploy scripts led to copying ZWESIS01 to the load library without all executable information. This made the system loader ABEND and ZWESIS01 wouldn't start.

However, if previously a valid ZWESIS01 has been deployed, the system will find a copy of it in LPA and use it. The check that verifies that we have the module in STEPLIB succeeds (because there is such load module, although it's unsable) and we keep using the LPA copy. Since we use IDENTIFY to attach the command handler TCB, we'd IDENTIFY a piece of LPA code and the subsequent ATTACH call would fail with ABEND S206-34 leaving ZWESIS01 without the modify command handler.

We need to verify that STEPLIB has a valid ZWESIS01. That can be done by using LOAD with LSEARCH=YES. If it fails, we've been loaded from the LPA copy and should print an error message and terminate.

**Comment by gadyck** [comment]
Irek,
________________________________

**Comment by gadyck** [comment]
Irek,
A better solution might be to do a BLDL against the module and verify that the *Not Executable" (NE) flag is *off* in the DE information. I would also check for any other required attributes, such as (I am assuming) RENT and REUS.
Regards, Greg

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by brooklynakos** [comment]
Hi there.
Regarding the ZWESIS01 load module,i find the Zowe documentation incorrect.
It states that "You can copy the ZWESIS01 file to your zwes_loadlib data set by using the command cp ZWESIS01 "//'zwes_loadlib(ZWESIS01)'". The zwes_loadlib must be a PDSE due to language requirements." but this will produce an non executable load module regardless of the destination library type (PDSE or not).
I think that the correct command should be cp  -X  ZWESIS01 "//'zwes_loadlib(ZWESIS01)'"
where -X specifies that the data to be copied is an executable.
Please verify and update the documentation accordingly.
Regards

**Comment by ifakhrutdinov** [comment]
@brooklynakos, that's correct. We changed that to have ```-X``` in the script https://github.com/zowe/zowe-install-packaging/blob/master/scripts/zss/zowe-xmem-deploy-loadmodule.sh#L46

The doc will need to be update too. Thanks for noticing that.

On the other hand, I've never had issues when I used ```cp``` without ```-X```.

**Comment by brooklynakos** [comment]
> @brooklynakos, that's correct. We changed that to have `-X` in the script https://github.com/zowe/zowe-install-packaging/blob/master/scripts/zss/zowe-xmem-deploy-loadmodule.sh#L46
> 
> The doc will need to be update too. Thanks for noticing that.
> 
> On the other hand, I've never had issues when I used `cp` without `-X`.

@ifakhrutdinov unfortunately i chose to manually APF authorise my load library ,so i did not use the zowe-install-apf-server.sh (and thus the included zowe-xmem-deploy-loadmodule.sh which contains the correct command).So i could not use the load module (the ZWESIS01 procedure abended and in addition the AMBLIST utility reported that the module was invalid).So i think that the documentation should be updated to save people from this kind of trouble.

**Comment by ifakhrutdinov** [comment]
@brooklynakos I opened a PR for the cp command in the doc, https://github.com/zowe/docs-site/pull/524

As for the PDSE requirements, I'll open an issue and we'll take a closer look at what needs to be documented (besides BLKSIZE we may want to add more details).

**Comment by ifakhrutdinov** [comment]
#146 solved the problem (non private module getting IDENTIFY'd) which had been the reason to open this issue. Closing.
