### ISSUE TITLE
Issue on 64 bit calling function dynallocAllocDataset/AllocIntReader

### ISSUE THREAD

**Issue by ojcelis** [zowe/zowe-common-c#302]
During PR402 testing. I did test on 64-bit build and found an issue when my new service (jesService) I'm working is calling AllocIntReader.

Error Message: 500 DYNALLOC failed with RC = 9, DYN RC = 12, RSN = 0x036C0000

**Comment by JoeNemo** [comment]
Hard to reproduce and no plan made to address this.
