### ISSUE TITLE
ZIS is failing and documentation provides no clue why

### ISSUE THREAD

**Issue by JirkaAichler** [zowe/zowe-common-c#320]
The output of zssServer.log:

```
ZWES1013I ZSS Server has started. Version '2.2.0+20220713' 31-bit
fallback to default server settings
ZWES1038I Server timeouts file '/z/apimlpc/api-layer-idt-perf/zowe/v2.2.0/instance/workspace/app-server/serverConfig/timeouts.json' either not found or invalid JSON. ZSS sessions will use the default length of one hour.
ZWES1061I TLS settings: keyring '/z/apimlpc/api-layer-idt-perf/zowe/zowe-keystore/localhost/localhost.keystore.p12', label 'localhost', password '****', stash '(no stash)'
ZWES1101I Product Registration is disabled.
ZWES1035I ZSS Server settings: Address='0.0.0.0', port='40010', protocol='https'
ZWES1064I Caching Service not configured
ZWES1600I JWT will be configured using JWK URL https://hostname:40005/gateway/api/v1/auth/keys/public/current
ZWES1039I Installing 'VSAM dataset contents' service...
ZWES1039I Installing 'dataset metadata' service...
ZWES1039I Installing 'dataset contents' service...
ZWES1014I ZIS status - 'Failure' (name='ZWESIS_CA32PRD  ', cmsRC='47', description='ZVT is NULL', clientVersion='2')
ZWES1606W Failed to get JWK - failed to send HTTP request, retry in 30 seconds
ZWES1606W Failed to get JWK - HTTP response error, retry in 30 seconds
ZWES1601I Server is ready to accept JWT without fallback to legacy tokens
```

How do I fix it?

The message itself provides no action. The documentation also does not provide anything helpful.

https://docs.zowe.org/stable/troubleshoot/app-framework/zss-error-codes/#zwes0014i

Why it is an information message when it is a failure?

**Comment by 1000TurquoisePogs** [comment]
Likely ZIS is not started. Try running the ZWESISTC, it does not get started the same time as the rest of zowe.

**Comment by JirkaAichler** [comment]
Thank you, it helped!

Keeping the issue open to improve the messaging and documentation. The current messages look rather debug than customer-facing.

I would also improve the following message:
```
λ http post https://hostname.net:40010/saf/authenticate username=* pass=* applid=ZOWEAPPL --verify no
HTTP/1.1 500 Internal Server Error
Cache-control: no-store
Connection: keep-alive
Content-Type: application/json
Keep-Alive: max=1000
Pragma: no-cache
Server: jdmfws
Transfer-Encoding: chunked

{
    "error": "Check zssServer log for more details"
}
```

The message should indicate to the user what is happening. Not every API user is an admin who has access to logs.

**Comment by 1000TurquoisePogs** [comment]
The documentation says what I said though,

>   In the cases listed below check that the ZWESISTC started task is running. If not, start it with the TSO command `/S ZWESISTC`:
  - `cmsRC=12`, description=`'Global area address is NULL'`
  - `cmsRC=39`, description=`'Cross-memory server abended'`
  - `cmsRC=47`, description=`'ZVT is NULL'`
  - `cmsRC=64`, description=`'PC is unavailable'`

If you can think of a better way to word that, you can edit the page here:
https://github.com/zowe/docs-site/edit/docs-staging/docs/troubleshoot/app-framework/zss-error-codes.md
I'm not sure the exact meanings of the 4 different codes, but I've been taught the same thing that the doc says: those 4 generally mean ZIS isn't running.

**Comment by JirkaAichler** [comment]
You are right but I had no idea that this STC is not run automatically during Zowe startup. In my case, it has also a different name so it was a little bit more difficult to find it.

**Comment by ifakhrutdinov** [comment]
This will be addressed in https://github.com/zowe/zss/issues/717.
