### ISSUE TITLE
Debug message 'wow'

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-common-c#361]
**Describe the bug**

This debug message is not very helpful: https://github.com/zowe/zowe-common-c/blob/541462f70ceff3ca0066aacc203b03df50cdd3d4/c/httpserver.c#L4982

**Steps to Reproduce**

1. `zss.logLevels._zss.httpserver=5`

**Expected behavior**

- Remove this debug message
- Or update it with something useful
- Or explain if `wow` is special acronym, because this looks like forgotten debug line 😄 

**Logs**
```
wow
parse URL mask loop top len=57 slashPos=5 prevSlashPos=0 partLen=5
wow
parse URL mask loop top len=57 slashPos=13 prevSlashPos=5 partLen=8
wow
parse URL mask loop top len=57 slashPos=34 prevSlashPos=13 partLen=21
wow
parse URL mask loop top len=57 slashPos=43 prevSlashPos=34 partLen=9
wow
```

**Describe your environment**
- Zowe 2.x

**Comment by 1000TurquoisePogs** [comment]
it certainly is a prehistoric debug line. zss had many such lines and can be removed or replaced with something better.

**Comment by Martin-Zeithaml** [comment]
So this one can be deleted. There is a loop over the URL with meaningful debug message already. I will do it once I have some free time.
