### ISSUE TITLE
Embeddedjs zos library symbol resolution support

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-common-c#363]
It would be convenient for certain properties of zowe.yaml to contain symbols that are resolved.
Imagine you want to state the hostname of something.
If we had 
```
zowe:
  externalDomains:
    - ${{ zoslib.getSymbol('&hostname') }}
```

I think that would be great.
It looks like the call that is needed for symbol resolution is https://www.ibm.com/docs/en/zos/2.5.0?topic=hsp-asasymbm-asasymbf-substitute-text-symbols so it would be a good addition to the codebase and would be reused for other things (dataset api needs symbol resolution on volser)

**Comment by 1000TurquoisePogs** [comment]
This code was just merged to configmgr, so hopefully the capability will be in 2.9.
at that point, it'll just be a matter of leveraging it in the yamls.
the function is zos.resolveSymbol('&thing')

**Comment by arthurcoucker** [comment]
@1000TurquoisePogs 

This is a very useful enhancement! Could it be that it was accidentally left out of the Zowe documentation, or am I overlooking it?
