### ISSUE TITLE
Space or colon in zowe.yaml file name

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-common-c#386]
**Describe the bug**

The config path with spaces, colon or very creative name causes error.

**Steps to Reproduce**

1. Get valid zowe.yaml file:
-  Rename it to `zo we.yaml` or
- `zo:we.yaml` or
- `FILE(PARMLIB(MY.ZOWE(YAML))`

2. Try some `zwe` command or start zowe via launcher with `CONFIG=some of the wrong zowe files`

**Expected behavior**

Easy to describe the bug, hard to suggest clever solution. This is not worth to rewrite the `configmgr.c` path parsing logic to be perfect. 
The space in launcher's `STDENV CONFIG=` seems to be considered as end of string (I don't know how to escape it). Similar to colon, which is used as path separator.
We should probably only update a documentation, that space and colon are not recommended to use in zowe.yaml file name.

**Additional context**
The only real problem is the "creative" name. But I not am expecting usage of such name in production.

**Quiz time**
Assume `stc.cm.er.yaml` is invalid and `stc.cm.ok.yaml` is valid config. What will be returned by `zwe config validate -c FILE(stc.cm.er.yaml)`?

```
ls -al
lrwxrwxrwx   1        14 Jul 17 06:53 FILE(stc.cm.er.yaml) -> stc.cm.ok.yaml
-rwxr-xr-x   1       507 Jun 27 07:01 stc.cm.er.yaml
-rwxr-xr-x   1       922 Jul 14 04:29 stc.cm.ok.yaml
```

**Comment by 1000TurquoisePogs** [comment]
`=(:` are used by the parser of finding files in the list so i treat them as reserved.
i don't know why space would be an issue. perhaps something/someone isn't using quotes to wrap CLI input.

**Comment by 1000TurquoisePogs** [comment]
also this: `FILE(stc.cm.er.yaml) -> stc.cm.ok.yaml` should be processed as `FILE(FILE(stc.cm.er.yaml))`, not as `stc.cm.er.yaml` so if that even works, it shouldn't be reading the `er` file.

**Comment by Martin-Zeithaml** [comment]
I don't know how to escape the spaces, I was not able to successfully start zowe with something like this:
```
//STDENV   DD  *                    
_CEE_ENVFILE_CONTINUATION=+         
CONFIG=/z/zeima02/_z 2 9 0
```
I tried backslash before spaces, different apostrophes, adding `FILE` keyword etc., but no success.
Same behavior for `zwe` command, no matter what, first space seems to end input:
`Error: Could not set config path for FILE("/z/zeima02/_z, status=4`

And `zwe config validate -c FILE(stc.cm.er.yaml)` is returning invalid config, so it is treated as `stc.cm.er.yaml` enclosed in `FILE()`.

**Comment by Martin-Zeithaml** [comment]
It seems, that `=():` are reserved. There is an [regex for path element](https://github.com/zowe/zowe-common-c/blob/9ed701fbaffd500119f6be0db9bb33d5eb2848df/c/configmgr.c#L432), which is expecting the closing `)` as the last char.

This (very bad) example is working, when the file is qualified with current dir, full path or enclosed in `FILE()`:
```
lrwxrwxrwx  FILE(stc.cm.er.yaml -> stc.cm.ok.yaml

zwe config validate -c './FILE(stc.cm.er.yaml' -> Valid config
zwe config validate -c '/full/path/FILE(stc.cm.er.yaml' -> Valid config
zwe config validate -c 'FILE(FILE(stc.cm.er.yaml)' -> Valid config
zwe config validate -c 'FILE(stc.cm.er.yaml' -> Error: Could not set config path for FILE(stc.cm.er.yaml, status=4
```

My suggestion is to update doc only with a note, that those reserved chars are not recommended to use.

I will do some research and testing for space(s) problem.

**Comment by Martin-Zeithaml** [comment]
The problem was sitting on my chair...
I was using a script for zwe script, so I was wrongly passing arguments to my script.
File with spaces was treated as arguments separated with spaces.
Direct calling of e.g. `zwe config validate -c 'FILE(file with spaces yaml)'` was ok.

**Comment by JoeNemo** [comment]
Not really an issue, more doc or misuse than anything else.
