### ISSUE TITLE
WTO messages are broken in ZIS v2.11.0

### ISSUE THREAD

**Issue by ifakhrutdinov** [zowe/zowe-common-c#406]
**Describe the bug**

**Steps to Reproduce**

1. Start ZIS
2. Look for the WTO message `ZWES0001I` in JESMSGLG
3. Formatting is completely broken

```
ZWES0001I ZSS Cross-Memory Server starting, version is 1004045136.1004045136.1004045128+-957029695
```

**Expected behavior**

The message should look like this
```
ZWES0001I ZSS Cross-Memory Server starting, version is 2.10.0+20230712
```

This affects all the plugins which use `wtoPrintf` (both statically and via dynamic linkage).

**Logs**

**Describe your environment**

Zowe v2.11.0

**Additional context**
Likely caused by https://github.com/zowe/zowe-common-c/pull/391

**Comment by ifakhrutdinov** [comment]
@DivergentEuropeans 
* Based on the way how it's used, I think the wtoPrintf3 function should have used different arguments
```diff
- void wtoPrintf3(const char *formatString, ...);
+ void wtoPrintf3(const char *formatString, va_list arg);
```
* How much did you test the changes?

CC: @JoeNemo , @1000TurquoisePogs

**Comment by DivergentEuropeans** [comment]
@ifakhrutdinov Is it broken for ZSS too? 

I tested for ZSS and it was working in the beginning. It's possible it broke during the code review refactor, either for ZIS or both. I probably checked for log to appear but didn't scroll through the args in the final days of testing. Thanks @ifakhrutdinov , good catch. We have another important priority I'll be working on next sprint when I come back from PTO so we'll either assign this to myself or to someone else
