### ISSUE TITLE
build/build_configmgr.sh: COMMON not initialized

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-common-c#410]
We are trying to use a [variable](https://github.com/zowe/zowe-common-c/blob/4b3aa89fbf8cb31e7df3511038e083ee99eb5871/build/build_configmgr.sh#L17C11-L17C11) in path for remove command:

`rm -f "${COMMON}/bin/configmgr"`

Because the variable `COMMON` was not initialized at that point, the value will be:
* Nothing -> we will try to delete from `/bin`
* Something -> for example accidentally initialized by user in unix profile -> bad things can happen

**Comment by JoeNemo** [comment]
We should remove this old build script soon.

**Comment by JoeNemo** [comment]
Obsolete
