### ISSUE TITLE
Member name length: schema validation vs configmgr

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-common-c#430]
Generally any member in config, which is/will be validated by [server-common#zoweDatasetMember](https://github.com/zowe/zowe-install-packaging/blob/468aeb3eec72d7bf83f558b534543205bb4425a6/schemas/server-common.json#L27), is expected to be 1 to 8 chars.

When using `PARMLIB` as config, the member name is [expected to be 3 to 8 chars](https://github.com/zowe/zowe-common-c/blob/40fd575d46ef6155317fda1fd953503400509eb5/c/configmgr.c#L776):

```
zwe config validate -c "PARMLIB(JOKER01.ZOWE.PR#3718.YAML(A))"
Error: Could not set parmlib member name for A, status=6
```

From the user point of view, member name validation should be the same no matter which/where/how component is running.

Would not be better to unify this?
Or is there some technical need for min length of 3?

**Comment by JoeNemo** [comment]
It is ok to make the lower limit 1 character in all places.
