### ISSUE TITLE
configmgr yaml-to-json converts null to empty string

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-common-c#435]
https://yaml.org/type/null.html

Consider this yaml:

```yaml
configs:
  sslDebug: ""
  apimlId:
```

It should parse to  json as

```json
"configs": {
  "sslDebug": "",
  "apimlId": null
}
```

But instead, the null becomes ""

Our code uses tags plus scalar content to determine if something should or shouldn't be null:
https://github.com/zowe/zowe-common-c/blob/v2.x/staging/c/yaml2json.c#L582-L586
However, a null tag is never seen, and the check for if a scalar is of a certain type does not say size=0 = null
I think that's okay, because size 0 scalars should be `""`
It seems the problem is we never get a null tag, but should.

**Comment by JoeNemo** [comment]
This seems like an oversight in my code.
