### ISSUE TITLE
os.sleep is not sleeping enough

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-common-c#439]
```
import * as os from 'cm_os';
const loopStart = Date.now();
os.sleep(10000);
const loopEnd = Date.now();
console.log('Time elapsed', `${new Date(loopEnd-loopStart).toISOString().slice(11,19)}`);
```
Returns `Time elapsed 00:00:00`.

Expectation: `Time elapsed 00:00:10`.

It seems, [usleep](https://github.com/JoeNemo/quickjs-portable/blob/f4d6ce3056346aed5e54b1bd866f673b8ab4b233/quickjs-libc.c#L2683) has limitation for time interval to be from `0` to `1,000,000`.

The impact is `os.sleep` works for `1..999` miliseconds.

**Comment by 1000TurquoisePogs** [comment]
unknown if this fixes it. testing now https://github.com/JoeNemo/quickjs-portable/pull/8
