### ISSUE TITLE
Embedded JS: colon in string is a game changer

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-common-c#456]
Let's define `zowe.yaml` as:
```
zowe:
  environments:
    test: ${{ "A B" }}
```
Run command to get value of `zowe.environments.test`:
```
zowe/runtime/2.16.0/bin/zwe config get -c ./zowe.yaml --path '.zowe.environments.test'
Temporary directory '/tmp/.zweenv-780' created.
Zowe will remove it on success, but if zwe exits with a non-zero code manual cleanup would be needed.
A B
Temporary directory /tmp/.zweenv-780 removed successfully.
```

Modify `zowe.yaml`, add colon inside the string:
```
zowe:
  environments:
    test: ${{ "A: B" }}
```
```
ZWEL0318E - Couldn't scan file '/zowe.yaml': mapping values are not allowed in this context at line 3, column 19.
Error: Could not load config for FILE(/zowe.yaml), status=2
```

**Note:**
* `test: ${{ 'A: B' }}`, `test: ${{ "A\: B" }}` returning same error

**Ugly workaround:**
```
zowe:
  environments:
    colon: ':'
    test: ${{ 'A' + zowe.environments.colon + ' B' }}
```
**Do not ask:**
* Will this solve your problem? `test: "A: B"` No, because I need to have a string with colon inside embedded JS. I have found this problem with more complex definition, but I have reduced the example to the minimum.

**Comment by 1000TurquoisePogs** [comment]
Have you tried `"${{ 'A: B' }}"`

**Comment by Martin-Zeithaml** [comment]
Yes, see **Note**, **Ugly Workaround** and **Do not ask**.

**Comment by Martin-Zeithaml** [comment]
Yes, of course, I forgot the double quotes.
