### ISSUE TITLE
Debug message `bos extend currSize` part of the `zwe` command output

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/zowe-common-c#490]
Originally found in [4005](https://github.com/zowe/zowe-install-packaging/issues/4005).

A certain size of config file causes printing of debug message `bos extend currSize=0x0 dataSize=0xaaaa chunk=0x1000 extend=0xbbbb` to `stdout`.

This makes a scripting automation challenging. 

The debug message should respect `zwe` verbose mode or be removed or something else.

**Comment by JoeNemo** [comment]
Closed as fixed in PR.
